Proof of concept
JE-FH/Jomsole pull request #2
Opened 2023-03-07 08:09 UTC by JE-FH

2023-03-07 11:22 UTC, MJHC requested changes
Crashes when inputting something that is not a program ie "hello" world panics. "ls" works fine. 

And shouldn't the interfaces be named traits because it is in rust? 

There is also a lot of uneccessary parantheses in the if statements. If you do not care about warnings, then its fine. 

should probably fix the unexpected panic.

2023-03-07 11:22 UTC, MJHC commented on src/lib/Commands/ExecuteCommand.rs
> +            .expect("penis");
```suggestion
            .expect("benis");
```

2023-03-07 11:27 UTC, JE-FH commented on src/lib/Commands/ExecuteCommand.rs
> +            .expect("penis");
penis to benis suggestion is a good suggestion however interfaces are not interfaces per say, they just interface with terminal, so interface in this context does not mean OOP like interface but more of interacting with another thing like terminal. 

Warnings about code style is in my opinion stupid and only warnings impacting semantics will be considered.

I will also fix panics

2023-03-18 22:39 UTC, JE-FH commented
after many hours of work this should be kinda working, but only on windows, a linux or unix command resolver would be needed to get it working on mac or linux

2023-03-23 09:19 UTC, MJHC approved these changes
![bitmoji](https://sdk.bitmoji.com/render/panel/5b7bff30-d7cc-4141-9f91-d77fa135057f-466a3e1d-e4e7-4853-b38e-03492ffbebf6-v1.png?transparent=1&palette=1&width=246)

2023-03-23 12:46 UTC, merged